/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.c1212l.etm.ui;

import com.c1212l.etm.client.ui.*;
import com.c1212l.etm.dto.ChangePassword;
import com.c1212l.etm.dto.Login;
import com.c1212l.etm.ui.*;

/**
 *
 * @author Android21SDK
 */
public  class AdminUI extends javax.swing.JFrame {
    /**
     * 
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelHome = new javax.swing.JPanel();
        homePanel3 = new com.c1212l.etm.ui.HomePanel();
        panelTransfer = new javax.swing.JPanel();
        transferPanel1 = new com.c1212l.etm.ui.TransferPanel();
        panelEmpl = new javax.swing.JPanel();
        employeePanel1 = new com.c1212l.etm.ui.EmployeePanel();
        panelProject = new javax.swing.JPanel();
        projectPanel1 = new com.c1212l.etm.ui.ProjectPanel();
        panelDepartment = new javax.swing.JPanel();
        departmentPanel1 = new com.c1212l.etm.ui.DepartmentPanel();
        panelLocation = new javax.swing.JPanel();
        locationPanel1 = new com.c1212l.etm.ui.LocationPanel();
        panelAccountManager = new javax.swing.JPanel();
        adminPanel1 = new com.c1212l.etm.ui.AdminPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Transfer Managment");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 618, 1009, -1));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        panelHome.setPreferredSize(new java.awt.Dimension(990, 590));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelHome.add(homePanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        jTabbedPane1.addTab("Home", panelHome);

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 962, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transferPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transfer Employee", panelTransfer);

        javax.swing.GroupLayout panelEmplLayout = new javax.swing.GroupLayout(panelEmpl);
        panelEmpl.setLayout(panelEmplLayout);
        panelEmplLayout.setHorizontalGroup(
            panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmplLayout.setVerticalGroup(
            panelEmplLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmplLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employee Manager", panelEmpl);

        panelProject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelProject.add(projectPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Project Manager", panelProject);

        panelDepartment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelDepartment.add(departmentPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jTabbedPane1.addTab("Department Manager", panelDepartment);

        panelLocation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelLocation.add(locationPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, -1));

        jTabbedPane1.addTab("Location Manager", panelLocation);

        panelAccountManager.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelAccountManager.add(adminPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 970, -1));

        jTabbedPane1.addTab("Acount Manager", panelAccountManager);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 560));

        jMenu1.setText("File");

        jMenuItem5.setText("Change Password");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Report");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Contact");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1126, 629);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ChangePasswordUI changePasswordUI = new ChangePasswordUI();
        changePasswordUI.show();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.c1212l.etm.ui.AdminPanel adminPanel1;
    private com.c1212l.etm.ui.DepartmentPanel departmentPanel1;
    private com.c1212l.etm.ui.EmployeePanel employeePanel1;
    private com.c1212l.etm.ui.HomePanel homePanel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private com.c1212l.etm.ui.LocationPanel locationPanel1;
    private javax.swing.JPanel panelAccountManager;
    private javax.swing.JPanel panelDepartment;
    private javax.swing.JPanel panelEmpl;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLocation;
    private javax.swing.JPanel panelProject;
    private javax.swing.JPanel panelTransfer;
    private com.c1212l.etm.ui.ProjectPanel projectPanel1;
    private com.c1212l.etm.ui.TransferPanel transferPanel1;
    // End of variables declaration//GEN-END:variables
}
