/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.c1212l.etm.ui_new;

import com.c1212l.etm.bll.DepartmentBUS;
import com.c1212l.etm.bll.LocationBUS;
import com.c1212l.etm.bll.ProjectBUS;
import com.c1212l.etm.bll.TransferBUS;
import com.c1212l.etm.bll.TransferTypeBUS;
import com.c1212l.etm.dal.DepartmentDAO;
import com.c1212l.etm.dal.LocationDAO;
import com.c1212l.etm.dto.Department;
import com.c1212l.etm.dto.Location;
import com.c1212l.etm.dto.Transfer;
import com.c1212l.etm.dto.TransferType;
import com.c1212l.etm.util.KeyValue;
import com.c1212l.etm.util.MyUtil;
import java.sql.Date;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DUONGHM
 */
public class PanelTransfer extends javax.swing.JPanel {

    /**
     * Creates new form PanelTransfer
     */
    public PanelTransfer() {
        initComponents();
        reloadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        panelInfor = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLetter = new javax.swing.JTextArea();
        panelTotalInfor = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        toolBarButton = new javax.swing.JToolBar();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnDisapprove = new javax.swing.JButton();
        panelBasicInfor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbFromDepartment = new javax.swing.JComboBox();
        jLabel37 = new javax.swing.JLabel();
        cmbFromLocation = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        cmbFromProject = new javax.swing.JComboBox();
        txtTransferID = new javax.swing.JTextField();
        panelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTransferData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dcRequestDate = new com.toedter.calendar.JDateChooser();
        dcRelievingDate = new com.toedter.calendar.JDateChooser();
        dcJoiningDate = new com.toedter.calendar.JDateChooser();
        cbRelievingDateUnknown = new javax.swing.JCheckBox();
        cbJoiningDateUnknown = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        cmbToLocation = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cmbToDepartment = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        cmbToProject = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbTransferType = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        dcApproveDate = new com.toedter.calendar.JDateChooser();
        cbApproveDateUnknown = new javax.swing.JCheckBox();
        cmbApprove = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();

        panelInfor.setBorder(javax.swing.BorderFactory.createTitledBorder("Letter"));

        txtLetter.setColumns(20);
        txtLetter.setRows(5);
        txtLetter.setText("Thu nam o day");
        jScrollPane3.setViewportView(txtLetter);

        javax.swing.GroupLayout panelInforLayout = new javax.swing.GroupLayout(panelInfor);
        panelInfor.setLayout(panelInforLayout);
        panelInforLayout.setHorizontalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelInforLayout.setVerticalGroup(
            panelInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInforLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelTotalInfor.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Information"));

        jLabel29.setText("Total Transfer Request");

        jLabel30.setText("Total Approve");

        jLabel31.setText("Total Disapprove");

        jLabel32.setText("jLabel32");

        jLabel33.setText("jLabel33");

        jLabel34.setText("jLabel34");

        jLabel35.setText("Total Waiting Approve");

        jLabel36.setText("jLabel36");

        javax.swing.GroupLayout panelTotalInforLayout = new javax.swing.GroupLayout(panelTotalInfor);
        panelTotalInfor.setLayout(panelTotalInforLayout);
        panelTotalInforLayout.setHorizontalGroup(
            panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jLabel35))
                .addGap(18, 18, 18)
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTotalInforLayout.setVerticalGroup(
            panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTotalInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTotalInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTotalInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTotalInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(leftPanel);

        toolBarButton.setRollover(true);

        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_new/save_32.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setFocusable(false);
        btnUpdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        toolBarButton.add(btnUpdate);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_new/delete_32.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        toolBarButton.add(btnDelete);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1380633043_gtk-cancel.png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setFocusable(false);
        btnRefresh.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        toolBarButton.add(btnRefresh);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_new/find.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        toolBarButton.add(btnSearch);

        btnApprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_new/badge_tick.png"))); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.setFocusable(false);
        btnApprove.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnApprove.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        toolBarButton.add(btnApprove);

        btnDisapprove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_new/delete1.png"))); // NOI18N
        btnDisapprove.setText("Disapprove");
        btnDisapprove.setFocusable(false);
        btnDisapprove.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnDisapprove.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDisapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisapproveActionPerformed(evt);
            }
        });
        toolBarButton.add(btnDisapprove);

        panelBasicInfor.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Information"));

        jLabel1.setText("Employee Number");

        txtNumber.setText("jTextField1");

        jLabel2.setText("Employee Name");

        txtName.setText("jTextField1");

        jLabel13.setText("Department");

        cmbFromDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFromDepartmentItemStateChanged(evt);
            }
        });

        jLabel37.setText("Location");

        cmbFromLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFromLocationItemStateChanged(evt);
            }
        });

        jLabel38.setText("Project");

        cmbFromProject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFromProjectItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelBasicInforLayout = new javax.swing.GroupLayout(panelBasicInfor);
        panelBasicInfor.setLayout(panelBasicInforLayout);
        panelBasicInforLayout.setHorizontalGroup(
            panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicInforLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransferID, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel13)
                    .addComponent(jLabel37))
                .addGap(18, 18, 18)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbFromLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFromDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFromProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBasicInforLayout.setVerticalGroup(
            panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBasicInforLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFromLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cmbFromDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBasicInforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cmbFromProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTransferID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelTable.setBorder(javax.swing.BorderFactory.createTitledBorder("List Employee"));

        tbTransferData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTransferData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbTransferDataMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbTransferData);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTableLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Transfer Information"));

        jLabel3.setText("Request Date");

        jLabel4.setText("Relieving Date");

        jLabel5.setText("Joining Date");

        cbRelievingDateUnknown.setText("Null");

        cbJoiningDateUnknown.setText("Null");

        jLabel15.setText("To Location");

        cmbToLocation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbToLocationItemStateChanged(evt);
            }
        });

        jLabel14.setText("To Department ");

        cmbToDepartment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbToDepartmentItemStateChanged(evt);
            }
        });

        jLabel11.setText("To Project");

        cmbToProject.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbToProjectItemStateChanged(evt);
            }
        });

        jLabel6.setText("Transfer Type");

        cmbTransferType.setEnabled(false);
        cmbTransferType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmbTransferTypeKeyReleased(evt);
            }
        });

        jLabel7.setText("ApproveDate");

        cbApproveDateUnknown.setText("Null");

        cmbApprove.setEnabled(false);

        jLabel8.setText("Approve");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dcRelievingDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcJoiningDate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcRequestDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcApproveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbJoiningDateUnknown)
                    .addComponent(cbRelievingDateUnknown)
                    .addComponent(cbApproveDateUnknown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(cmbToLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbToProject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbToDepartment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(22, 22, 22)
                        .addComponent(cmbTransferType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cmbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dcRequestDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(dcRelievingDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(dcJoiningDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbRelievingDateUnknown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbJoiningDateUnknown))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbToLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbToDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbToProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbApproveDateUnknown)
                            .addComponent(dcApproveDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTransferType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbApprove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toolBarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBasicInfor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addComponent(toolBarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBasicInfor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFromDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFromDepartmentItemStateChanged
    }//GEN-LAST:event_cmbFromDepartmentItemStateChanged

    private void cmbFromLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFromLocationItemStateChanged
    }//GEN-LAST:event_cmbFromLocationItemStateChanged

    private void cmbFromProjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFromProjectItemStateChanged
    }//GEN-LAST:event_cmbFromProjectItemStateChanged

    private void cmbToLocationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbToLocationItemStateChanged
    }//GEN-LAST:event_cmbToLocationItemStateChanged

    private void cmbToDepartmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbToDepartmentItemStateChanged
        updateCmbLocationByCmbDepartment();
    }//GEN-LAST:event_cmbToDepartmentItemStateChanged

    private void cmbToProjectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbToProjectItemStateChanged
    }//GEN-LAST:event_cmbToProjectItemStateChanged

    private void cmbTransferTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbTransferTypeKeyReleased
    }//GEN-LAST:event_cmbTransferTypeKeyReleased

    private void tbTransferDataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTransferDataMouseReleased
        updateFieldWhenSelectTransfer();
    }//GEN-LAST:event_tbTransferDataMouseReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (txtTransferID.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please select Transfer ID");
        } else {
            try {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Delete", JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION) {
                    transferBUS.deleteTransfer(Integer.parseInt(txtTransferID.getText()));
                    reloadData();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            if (txtTransferID.getText().equals("")) {
                throw new Exception("Please select Transfer ID");
            }
            int transferID = Integer.parseInt(txtTransferID.getText());
            int transferTypeID = ((KeyValue) cmbTransferType.getSelectedItem()).getKey();
            /*
             Date requestDate = Date.valueOf(txtRequestDate.getText());
             String reason = txtReason.getText();
             Date approveDate = Date.valueOf(txtApproveDate.getText());
             int approve = ((KeyValue) cmbApprove.getSelectedItem()).getKey();
             */
            String relDate = MyUtil.getDateStr(dcRelievingDate, cbRelievingDateUnknown);
            String joinDate = MyUtil.getDateStr(dcJoiningDate, cbJoiningDateUnknown);
            int fromProjectID = ((KeyValue) cmbFromProject.getSelectedItem()).getKey();
            int toProjectID = ((KeyValue) cmbToProject.getSelectedItem()).getKey();
            int fromDepartmentID = ((KeyValue) cmbFromDepartment.getSelectedItem()).getKey();
            int toDepartmentID = ((KeyValue) cmbToDepartment.getSelectedItem()).getKey();
            int formLocationID = ((KeyValue) cmbFromLocation.getSelectedItem()).getKey();
            int toLocationID = ((KeyValue) cmbToLocation.getSelectedItem()).getKey();

            int approve = ((KeyValue) cmbApprove.getSelectedItem()).getKey();

            transferBUS.updateTransfer(transferID, transferTypeID, relDate, joinDate, fromProjectID, toProjectID, fromDepartmentID, toDepartmentID, formLocationID, toLocationID, approve);

            reloadData();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        try {
            int transferID = Integer.parseInt(txtTransferID.getText());
            transferBUS.approveTransfer(transferID);
            reloadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnDisapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisapproveActionPerformed
        try {
            int transferID = Integer.parseInt(txtTransferID.getText());
            transferBUS.disapproveTransfer(transferID);
            reloadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnDisapproveActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        reloadData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadSearchData();
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDisapprove;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbApproveDateUnknown;
    private javax.swing.JCheckBox cbJoiningDateUnknown;
    private javax.swing.JCheckBox cbRelievingDateUnknown;
    private javax.swing.JComboBox cmbApprove;
    private javax.swing.JComboBox cmbFromDepartment;
    private javax.swing.JComboBox cmbFromLocation;
    private javax.swing.JComboBox cmbFromProject;
    private javax.swing.JComboBox cmbToDepartment;
    private javax.swing.JComboBox cmbToLocation;
    private javax.swing.JComboBox cmbToProject;
    private javax.swing.JComboBox cmbTransferType;
    private com.toedter.calendar.JDateChooser dcApproveDate;
    private com.toedter.calendar.JDateChooser dcJoiningDate;
    private com.toedter.calendar.JDateChooser dcRelievingDate;
    private com.toedter.calendar.JDateChooser dcRequestDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel panelBasicInfor;
    private javax.swing.JPanel panelInfor;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTotalInfor;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tbTransferData;
    private javax.swing.JToolBar toolBarButton;
    private javax.swing.JTextArea txtLetter;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtTransferID;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel tblModel;
    ArrayList<Transfer> lstTransfer;
    TransferBUS transferBUS = new TransferBUS();

    private void initTable() {
        Vector header = new Vector();
        header = new Vector();
        //---Ko hien thi
        header.add("ID");
        header.add("Type");
        //------------------------------------
        header.add("Employee Number");
        header.add("Name");
        //---Ko hien thi        
        header.add("Relieving Date");
        header.add("Joining Date");
        header.add("Request Date");
        header.add("Reason");
        header.add("Approve Date");
        //------------------------------------        
        header.add("From Project");
        header.add("To Project");
        header.add("From Department");
        header.add("To Department");
        header.add("From Location");
        header.add("To Location");
        header.add("Appove");
        header.add("Letter");
        tblModel = new DefaultTableModel(header, 0);
        tbTransferData.setModel(tblModel);

        makeInvisibleColumn(0);
        makeInvisibleColumn(1);
        makeInvisibleColumn(4);
        makeInvisibleColumn(5);
        makeInvisibleColumn(6);
        makeInvisibleColumn(7);

    }

    private void makeInvisibleColumn(int col) {
        tbTransferData.getColumnModel().getColumn(col).setMaxWidth(0);
        tbTransferData.getColumnModel().getColumn(col).setMinWidth(0);
        tbTransferData.getColumnModel().getColumn(col).setPreferredWidth(0);
        tbTransferData.getColumnModel().getColumn(col).setResizable(false);
    }

    private void fillData(ArrayList<Transfer> lst) {
        if (lst != null) {
            for (Transfer transfer : lst) {
                tblModel.addRow(transfer.getVector());
            }
        }
    }

    private void initCmbTransferType() throws ClassNotFoundException, SQLException {
        cmbTransferType.removeAllItems();
        cmbTransferType.addItem(new KeyValue(-1, ""));
        TransferTypeBUS transferTypeBUS = new TransferTypeBUS();
        ArrayList<TransferType> arrTransferType = transferTypeBUS.getAllTransferType();
        for (TransferType transferType : arrTransferType) {
            cmbTransferType.addItem(new KeyValue(transferType.getTransferTypeID(), transferType.getTransferTypeName()));
        }
    }

    private void initCmbFromProject() throws ClassNotFoundException, SQLException {
        cmbFromProject.removeAllItems();
        cmbFromProject.addItem(new KeyValue(-1, ""));
        ProjectBUS projectBUS = new ProjectBUS();
        ArrayList<com.c1212l.etm.dto.Project> arrProject = projectBUS.getAllProject();
        for (com.c1212l.etm.dto.Project p : arrProject) {
            cmbFromProject.addItem(new KeyValue(p.getProjectID(), p.getProjectName()));
        }
    }

    private void initCmbToProject() throws ClassNotFoundException, SQLException {
        cmbToProject.removeAllItems();
        cmbToProject.addItem(new KeyValue(-1, ""));
        ProjectBUS projectBUS = new ProjectBUS();
        ArrayList<com.c1212l.etm.dto.Project> arrProject = projectBUS.getAllProject();
        for (com.c1212l.etm.dto.Project p : arrProject) {
            cmbToProject.addItem(new KeyValue(p.getProjectID(), p.getProjectName()));
        }
    }

    private void initCmbFromLocation() throws ClassNotFoundException, SQLException {
        cmbFromLocation.removeAllItems();
        cmbFromLocation.addItem(new KeyValue(-1, ""));
        LocationBUS locationBUS = new LocationBUS();
        ArrayList<Location> arrLocation = locationBUS.getAllLocation();
        for (Location location : arrLocation) {
            cmbFromLocation.addItem(new KeyValue(location.getLocationID(), location.getLocationName()));
        }
    }

    private void initCmbToLocation() throws ClassNotFoundException, SQLException {
        cmbToLocation.removeAllItems();
        cmbToLocation.addItem(new KeyValue(-1, ""));
        LocationBUS locationBUS = new LocationBUS();
        ArrayList<Location> arrLocation = locationBUS.getAllLocation();
        for (Location location : arrLocation) {
            cmbToLocation.addItem(new KeyValue(location.getLocationID(), location.getLocationName()));
        }
    }

    private void initCmbFromDepartment() throws ClassNotFoundException, SQLException {
        cmbFromDepartment.removeAllItems();
        cmbFromDepartment.addItem(new KeyValue(-1, ""));
        DepartmentBUS departmentBUS = new DepartmentBUS();
        LocationDAO locationDAO = new LocationDAO();
        ArrayList<Department> arrDepartment = departmentBUS.getAllDepartment();
        for (Department department : arrDepartment) {
            Location location = locationDAO.getLocationById(department.getLocationID());
            cmbFromDepartment.addItem(new KeyValue(
                    department.getDepartmentID(),
                    department.getDepartmentName() + " - " + location.getLocationName()));
        }
    }

    private void initCmbToDepartment() throws ClassNotFoundException, SQLException {
        cmbToDepartment.removeAllItems();
        cmbToDepartment.addItem(new KeyValue(-1, ""));
        DepartmentBUS departmentBUS = new DepartmentBUS();
        LocationDAO locationDAO = new LocationDAO();
        ArrayList<Department> arrDepartment = departmentBUS.getAllDepartment();
        for (Department department : arrDepartment) {
            Location location = locationDAO.getLocationById(department.getLocationID());
            cmbToDepartment.addItem(new KeyValue(
                    department.getDepartmentID(),
                    department.getDepartmentName() + " - " + location.getLocationName()));
        }
    }

    private void initCmbApprove() {
        cmbApprove.removeAllItems();
        cmbToDepartment.addItem(new KeyValue(-1, ""));
        cmbApprove.addItem(new KeyValue(1, "Approve"));
        cmbApprove.addItem(new KeyValue(2, "Disapprove"));
        cmbApprove.addItem(new KeyValue(3, "Waiting Approve"));
    }

    private void initTextfield() {
        txtName.setText("");
        txtNumber.setText("");
        txtTransferID.setText("");
    }

    private void reloadData() {
        try {
            initTextfield();
            initTable();
            initCmbTransferType();
            initCmbFromProject();
            initCmbToProject();
            initCmbFromDepartment();
            initCmbToDepartment();
            initCmbFromLocation();
            initCmbToLocation();
            initCmbApprove();
            //convertDate();            
            fillData(transferBUS.getAllTransfer());
//            initTextField();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private String checkFieldAndReturnTransferType() {
        int fromProjectID = ((KeyValue) cmbFromProject.getSelectedItem()).getKey();
        int toProjectID = ((KeyValue) cmbToProject.getSelectedItem()).getKey();
        int fromDepartmentID = ((KeyValue) cmbFromDepartment.getSelectedItem()).getKey();
        int toDepartmentID = ((KeyValue) cmbToDepartment.getSelectedItem()).getKey();
        int fromLocationID = ((KeyValue) cmbFromLocation.getSelectedItem()).getKey();
        int toLocationID = ((KeyValue) cmbToLocation.getSelectedItem()).getKey();

        int[] check = {0, 0, 0};

        if (fromProjectID != toProjectID) {
            check[0] = 1;
        }
        if (fromDepartmentID != toDepartmentID) {
            check[1] = 1;
        }
        if (fromLocationID != toLocationID) {
            check[2] = 1;
        }

        int sum = 0;
        for (int i = 0; i < check.length; i++) {
            sum += check[i];
        }

        if (sum == 0) {
            //Error: No transfer ?
            return "";
        } else if (sum == 1) {
            //Transfer only one
            if (check[0] == 1) {
                //Project
                return "Project Transfer";
            }
            if (check[1] == 1) {
                //Department
                return "Department Transfer";
            }
            if (check[2] == 1) {
                //Location
                return "Location Transfer";
            }
            //Unexpected Error
            return "";
        } else {
            //Custom transfer
            return "Custom Transfer";
        }
    }

    private void updateCmbTransferType() {
        cmbTransferType.setSelectedItem(new KeyValue(0, checkFieldAndReturnTransferType()));
    }

    private void updateFieldWhenSelectTransfer() {
        //boolean oldSearchMode = isSearchMode;
        //isSearchMode = false;
        int row = tbTransferData.getSelectedRow();

        txtTransferID.setText(tbTransferData.getValueAt(row, 0).toString());
        cmbTransferType.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 1).toString()));
        txtNumber.setText(tbTransferData.getValueAt(row, 2).toString());
        txtName.setText(tbTransferData.getValueAt(row, 3).toString());

        if (tbTransferData.getValueAt(row, 4) == null) {
            cbRelievingDateUnknown.setSelected(true);
        } else {
            cbRelievingDateUnknown.setSelected(false);
            dcRelievingDate.setDate(Date.valueOf(tbTransferData.getValueAt(row, 4).toString()));
        }

        if (tbTransferData.getValueAt(row, 5) == null) {
            cbJoiningDateUnknown.setSelected(true);
        } else {
            cbJoiningDateUnknown.setSelected(false);
            dcJoiningDate.setDate(Date.valueOf(tbTransferData.getValueAt(row, 5).toString()));
        }

        dcRequestDate.setDate(Date.valueOf(tbTransferData.getValueAt(row, 6).toString()));

        if (tbTransferData.getValueAt(row, 8) == null) {
            cbApproveDateUnknown.setSelected(true);
        } else {
            cbApproveDateUnknown.setSelected(false);
            dcApproveDate.setDate(Date.valueOf(tbTransferData.getValueAt(row, 8).toString()));
        }


        cmbFromProject.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 9).toString()));
        cmbToProject.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 10).toString()));
        cmbFromDepartment.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 11).toString()));
        System.out.println(tbTransferData.getValueAt(row, 11).toString());
        cmbToDepartment.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 12).toString()));
        cmbFromLocation.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 13).toString()));
        cmbToLocation.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 14).toString()));
        cmbApprove.setSelectedItem(new KeyValue(0, tbTransferData.getValueAt(row, 15).toString()));

        txtLetter.setText(tbTransferData.getValueAt(row, 16).toString());
        String approve = tbTransferData.getValueAt(row, 15).toString();

        btnApprove.setVisible(approve.equals("Waiting Approve"));
        btnDisapprove.setVisible(approve.equals("Waiting Approve"));



        updateCmbTransferType();
    }

    private void updateCmbLocationByCmbDepartment() {
        if (cmbToDepartment.getSelectedItem() != null) {
            int toDepartmentID = ((KeyValue) cmbToDepartment.getSelectedItem()).getKey();
            DepartmentDAO departmentDAO = new DepartmentDAO();
            Department department = departmentDAO.getDepartmentByID(toDepartmentID);
            if (department != null) {
                LocationDAO locationDAO = new LocationDAO();
                Location location = locationDAO.getLocationById(department.getLocationID());
                cmbToLocation.setSelectedItem(new KeyValue(location.getLocationID(), location.getLocationName()));
            } else {
                cmbToLocation.setSelectedItem(new KeyValue(-1, ""));
            }
        }
    }

    private void loadSearchData() {

        String condition = "";
        try {

            if (!txtNumber.getText().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where employeeNumber like '%" + txtNumber.getText() + "%' ";
                } else {
                    condition += " and employeeNumber like '%" + txtNumber.getText() + "%' ";
                }
            }

            if (!txtName.getText().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where employeeName like '%" + txtName.getText() + "%' ";
                } else {
                    condition += " and employeeName like '%" + txtName.getText() + "%' ";
                }
            }

            KeyValue fromProject = (KeyValue) cmbFromProject.getSelectedItem();
            if (fromProject != null && !fromProject.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where fromProjectID = " + fromProject.getKey() + " ";
                } else {
                    condition += " and fromProjectID = " + fromProject.getKey() + " ";
                }
            }

            KeyValue toProject = (KeyValue) cmbToProject.getSelectedItem();
            if (toProject != null && !toProject.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where toProjectID = " + toProject.getKey() + " ";
                } else {
                    condition += " and toProjectID = " + toProject.getKey() + " ";
                }
            }

            KeyValue fromDepartment = (KeyValue) cmbFromDepartment.getSelectedItem();
            if (fromDepartment != null && !fromDepartment.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where fromDepartmentID = " + fromDepartment.getKey() + " ";
                } else {
                    condition += " and fromDepartmentID = " + fromDepartment.getKey() + " ";
                }
            }

            KeyValue toDepartment = (KeyValue) cmbToDepartment.getSelectedItem();
            if (toDepartment != null && !toDepartment.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where toDepartmentID = " + toDepartment.getKey() + " ";
                } else {
                    condition += " and toDepartmentID = " + toDepartment.getKey() + " ";
                }
            }


            KeyValue fromLocation = (KeyValue) cmbFromLocation.getSelectedItem();
            if (fromLocation != null && !fromLocation.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where fromLocationID = " + fromLocation.getKey() + " ";
                } else {
                    condition += " and fromLocationID = " + fromLocation.getKey() + " ";
                }
            }

            KeyValue toLocation = (KeyValue) cmbToLocation.getSelectedItem();
            if (toLocation != null && !toLocation.getValue().equals("")) {
                if (!condition.contains("where")) {
                    condition += " where toLocationID = " + toLocation.getKey() + "";
                } else {
                    condition += " and toLocationID = " + toLocation.getKey() + "";
                }
            }

            //JOptionPane.showMessageDialog(null, condition);

            initTable();
            lstTransfer = transferBUS.searchTransfer(condition);
            fillData(lstTransfer);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            ex.printStackTrace();
        }

    }
}
