/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddEmployee.java
 *
 * Created on Nov 11, 2010, 10:14:15 AM
 */
package GUI;

import Bussiness.validateInfo;
import DataAccess.DepartmentDAO;
import DataAccess.EmployeeDAO;
import DataAccess.LocationDAO;
import DataAccess.ProjectDAO;
import Entity.Employee;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author THANHNX
 */
public class AddEmployee extends javax.swing.JDialog {

    private Employee objEmpl = null;

    /** Creates new form AddEmployee */
    public AddEmployee() throws SQLException {
        initComponents();
        loadLocation();
        loadDeparment();
        loadProject();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtEmployeeNumber = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        lblWorkPerience = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAddress = new javax.swing.JTextArea();
        lblGender = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox();
        lblAllowance = new javax.swing.JLabel();
        txtAllowance = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        cbLocation = new javax.swing.JComboBox();
        lblDepartment = new javax.swing.JLabel();
        cbDepartment = new javax.swing.JComboBox();
        lblProject = new javax.swing.JLabel();
        cbProject = new javax.swing.JComboBox();
        lblBirth = new javax.swing.JLabel();
        jDateBirthday = new com.toedter.calendar.JDateChooser();
        lblMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtWExp = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblTite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(1774, 720));

        jLabel2.setText("Number");

        lblName.setText("Name");

        txtFullName.setColumns(25);

        lblEmail.setText("Email");

        txtEmail.setColumns(25);

        lblPassword.setText("Password");

        lblRole.setText("Role");

        txtRole.setColumns(25);

        password.setColumns(25);

        lblWorkPerience.setText("Work Experience");

        lblAddress.setText("Address");

        txaAddress.setColumns(25);
        txaAddress.setRows(5);
        jScrollPane1.setViewportView(txaAddress);

        lblGender.setText("Gender");

        cbGender.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Male", "Female" }));

        lblAllowance.setText("Allowance");

        txtAllowance.setColumns(15);

        lblLocation.setText("Location");

        cbLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbLocation.setMinimumSize(new java.awt.Dimension(250, 18));
        cbLocation.setPreferredSize(new java.awt.Dimension(207, 20));

        lblDepartment.setText("Department");

        cbDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDepartment.setPreferredSize(new java.awt.Dimension(207, 20));

        lblProject.setText("Project");

        cbProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProject.setPreferredSize(new java.awt.Dimension(207, 20));

        lblBirth.setText("Birthday");

        lblMsg.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setText(null);

        jLabel1.setText("Year");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProject)
                            .addComponent(lblDepartment)
                            .addComponent(lblLocation)
                            .addComponent(lblAllowance)
                            .addComponent(lblGender)
                            .addComponent(lblBirth)
                            .addComponent(lblAddress))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(lblMsg)
                            .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLocation, 0, 222, Short.MAX_VALUE)
                            .addComponent(cbDepartment, 0, 222, Short.MAX_VALUE)
                            .addComponent(cbProject, 0, 222, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAllowance, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblWorkPerience)
                            .addComponent(lblRole)
                            .addComponent(lblPassword)
                            .addComponent(lblEmail)
                            .addComponent(lblName)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(txtRole, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtWExp, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(txtEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRole)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkPerience)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtWExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblBirth))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addComponent(cbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAllowance)
                    .addComponent(txtAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLocation)
                    .addComponent(cbLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDepartment)
                    .addComponent(cbDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProject)
                    .addComponent(cbProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMsg)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/delete.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/block.png"))); // NOI18N
        btnExit.setText("Cancel");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblTite.setFont(new java.awt.Font("Arial", 1, 14));
        lblTite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_user.png"))); // NOI18N
        lblTite.setText("Add Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTite, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnReset)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadLocation() throws SQLException {
        Vector v = new Vector();
        v = LocationDAO.getLocationFromDB();
        cbLocation.setModel(new DefaultComboBoxModel(v));
    }

    public void loadDeparment() throws SQLException {
        Vector v = new Vector();
        v = DepartmentDAO.getDepartmentFromDB();
        cbDepartment.setModel(new DefaultComboBoxModel(v));
    }

    public void loadProject() throws SQLException {
        Vector v = new Vector();
        v = ProjectDAO.getProjectFromDB();
        cbProject.setModel(new DefaultComboBoxModel(v));
    }

    public void insertEmployee() {
        try {
            objEmpl = new Employee();
            objEmpl.setEmployeeNumber(Integer.parseInt(txtEmployeeNumber.getText()));
            objEmpl.setEmployeeName(txtFullName.getText());
            objEmpl.setEmail(txtEmail.getText());
            objEmpl.setPassword(String.valueOf(password.getPassword()));
            objEmpl.setEmployeeRole(txtRole.getText());
            if (validateInfo.checkNumber(txtWExp.getText())) {
                objEmpl.setWorkExperience(Integer.parseInt(txtWExp.getText()));
            }
            objEmpl.setAddress(txaAddress.getText());
            objEmpl.setBirthday(jDateBirthday.getDate());
            objEmpl.setGender(cbGender.getSelectedIndex());
            if (validateInfo.checkNumber(txtAllowance.getText())) {
                objEmpl.setAllowance(Float.parseFloat(txtAllowance.getText()));
            }
            objEmpl.setLocationID(LocationDAO.getLocationID((String) cbLocation.getSelectedItem()));
            objEmpl.setDepartmentID(DepartmentDAO.getDepartmentID((String) cbDepartment.getSelectedItem()));
            objEmpl.setProjectID(ProjectDAO.getProjectID((String) cbProject.getSelectedItem()));
            EmployeeDAO.insertEmployee(objEmpl);
        } catch (SQLException ex) {
            Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (!validateInfo.checkNumber(txtEmployeeNumber.getText())) {
            lblMsg.setText("Please enter Employee number");
            txtEmployeeNumber.requestFocus();
            txtEmployeeNumber.requestFocus();
        } else if (!validateInfo.check(txtFullName.getText())) {
            lblMsg.setText("Please enter Name");
            txtFullName.requestFocus();
        } else if (!validateInfo.check(txtEmail.getText())) {
            lblMsg.setText("Please enter Email");
            txtEmail.requestFocus();
        } else if (!validateInfo.checkEmail(txtEmail.getText())) {
            lblMsg.setText("Wrong format Email");
            txtEmail.requestFocus();
        } else if (!validateInfo.check(password.getText())) {
            lblMsg.setText("Please enter Password");
            password.requestFocus();
        } else if (!validateInfo.check(txaAddress.getText())) {
            lblMsg.setText("Please enter Address");
            txaAddress.requestFocus();
        } else if (jDateBirthday.getDate() == null) {
            lblMsg.setText("Please enter birthdate");
        } else if (cbLocation.getSelectedIndex() == 0) {
            lblMsg.setText("Please select Location");
        } else if (cbDepartment.getSelectedIndex() == 0) {
            lblMsg.setText("Please select Department");
        } else if (cbProject.getSelectedIndex() == 0) {
            lblMsg.setText("Please select Project");
        } else {
            lblMsg.setText(null);
            insertEmployee();
            MainAdministrator.onLoadTableEmployee();
            JOptionPane.showMessageDialog(null, "Add Employee success");
            this.dispose();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtFullName.setText(null);
        txtEmail.setText(null);
        password.setText(null);
        txtRole.setText(null);
        txaAddress.setText(null);
        txtEmployeeNumber.setText(null);
        txtAllowance.setText(null);

    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    AddEmployee addEmployee = new AddEmployee();
                    addEmployee.setLocationRelativeTo(addEmployee);
                    addEmployee.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbDepartment;
    private javax.swing.JComboBox cbGender;
    private javax.swing.JComboBox cbLocation;
    private javax.swing.JComboBox cbProject;
    private com.toedter.calendar.JDateChooser jDateBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAllowance;
    private javax.swing.JLabel lblBirth;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblProject;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblTite;
    private javax.swing.JLabel lblWorkPerience;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextArea txaAddress;
    private javax.swing.JTextField txtAllowance;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeNumber;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtWExp;
    // End of variables declaration//GEN-END:variables
}
