/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Employee.java
 *
 * Created on Nov 7, 2010, 9:00:44 PM
 */
package GUI;

import Bussiness.TableModelTransferHistory;
import DataAccess.DepartmentDAO;
import DataAccess.LocationDAO;
import DataAccess.ProjectDAO;
import DataAccess.TransferDAO;
import Entity.Employee;
import Entity.Transfer;
import java.sql.SQLException;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Thanh
 */
public class MainEmployee extends javax.swing.JFrame {

    private TableModelTransferHistory tablemodelHistory = new TableModelTransferHistory();
    private Transfer objTransfer = null;
    private int transferID;
    private int employeeID;
    private int toProjectID;
    private int toLocationID;
    private int toDepartmentID;
    private String oldPassword;

    /** Creates new form Employee */
    public MainEmployee() {
        initComponents();
        try {
            loadDeparment();
            loadLocation();
            loadProject();
        } catch (SQLException ex) {
        }
    }

    public void LoadEmployee(Employee employee) {
        employeeID = employee.getEmployeeID();
        oldPassword = employee.getPassword();
        //load to table history
        tablemodelHistory.dataChanged();
        TransferDAO.loadToTableHistory(employeeID);
        lblEmailContent.setText(employee.getEmail());
        txtFullName.setText(employee.getEmployeeName());
        if (employee.getGender() == 1) {
            txtGender.setText("Male");
        } else if (employee.getGender() == 2) {
            txtGender.setText("Female");
        } else {
            txtGender.setText(null);
        }
        txtBirthday.setText(employee.getBirthday().toString());
        txtEmail.setText(employee.getEmail());
        txtAddress.setText(employee.getAddress());
        txtRole.setText(employee.getEmployeeRole());
        String currentDeparment = DepartmentDAO.getDepartmentName(employee.getDepartmentID());
        String currentProject = ProjectDAO.getProjectName(employee.getProjectID());
        String currentLocation = LocationDAO.getLocationName(employee.getLocationID());
        txtCurDeparment.setText(currentDeparment);
        txaCurLocation.setText(currentLocation);
        txtCurProject.setText(currentProject);
        txtEmployee.setText(employee.getEmployeeName());
        txtFromDepartment.setText(currentDeparment);
        txtFromProject.setText(currentProject);
        txaFromLocation.setText(currentLocation);
        txtRole.setText(employee.getEmployeeRole());
        txtSalary.setText(String.valueOf(employee.getAllowance()));
        txtWorkExprience.setText(String.valueOf(employee.getWorkExperience()));
    }

    public void loadLocation() throws SQLException {
        Vector v = new Vector();
        v = LocationDAO.getLocationFromDB();
        cbToLocation.setModel(new DefaultComboBoxModel(v));
    }

    public void loadDeparment() throws SQLException {
        Vector v = new Vector();
        v = DepartmentDAO.getDepartmentFromDB();
        cbToDepartment.setModel(new DefaultComboBoxModel(v));
    }

    public void loadProject() throws SQLException {
        Vector v = new Vector();
        v = ProjectDAO.getProjectFromDB();
        cbToProject.setModel(new DefaultComboBoxModel(v));
    }

    public void sendRequestTransfer() throws SQLException {
        objTransfer = new Transfer();
        int transferTypeID = 2;
        objTransfer.setTransferTypeID(transferTypeID);
        objTransfer.setEmployeeID(employeeID);
        int fromProjectID = ProjectDAO.getProjectID(txtFromProject.getText());
        int fromLocationID = LocationDAO.getLocationID(txaFromLocation.getText());
        int fromDepartmentID = DepartmentDAO.getDepartmentID(txtFromDepartment.getText());
        objTransfer.setFromProjectID(fromProjectID);
        objTransfer.setFromLocationID(fromLocationID);
        objTransfer.setFromDepartmentID(fromDepartmentID);
        objTransfer.setToProjectID(toProjectID);
        objTransfer.setToLocationID(toLocationID);
        objTransfer.setToDepartmentID(toDepartmentID);
        objTransfer.setReason(txaReason.getText());
        Date requestDate = new Date();
        objTransfer.setRequestDate(requestDate);
        objTransfer.setApprove("Waiting");
        TransferDAO.insertRequestTransfer(objTransfer);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblEmail = new javax.swing.JLabel();
        lblEmailContent = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnChangePass = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnHelp = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnAbout = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnLogoff = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBirthday = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCurDeparment = new javax.swing.JTextField();
        txtCurProject = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRole = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtWorkExprience = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSalary = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaCurLocation = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmployee = new javax.swing.JTextField();
        txtFromDepartment = new javax.swing.JTextField();
        txtFromProject = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaReason = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbToLocation = new javax.swing.JComboBox();
        cbToDepartment = new javax.swing.JComboBox();
        cbToProject = new javax.swing.JComboBox();
        btnRequest = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txaFromLocation = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistoryTransfer = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        btnViewHistoryDetails = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jChangePassEmployee = new javax.swing.JMenuItem();
        jLogout = new javax.swing.JMenuItem();
        jExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMPLOYEE SYSTEM");

        jToolBar1.setRollover(true);

        lblEmail.setText("Email   ");
        jToolBar1.add(lblEmail);

        lblEmailContent.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblEmailContent.setForeground(new java.awt.Color(255, 0, 0));
        lblEmailContent.setText(null);
        jToolBar1.add(lblEmailContent);
        jToolBar1.add(jSeparator3);

        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24x24/password.png"))); // NOI18N
        btnChangePass.setFocusable(false);
        btnChangePass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangePass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jToolBar1.add(btnChangePass);
        jToolBar1.add(jSeparator4);

        btnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24x24/help.png"))); // NOI18N
        btnHelp.setFocusable(false);
        btnHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHelp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHelp);
        jToolBar1.add(jSeparator1);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24x24/info.png"))); // NOI18N
        btnAbout.setFocusable(false);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);
        jToolBar1.add(jSeparator2);

        btnLogoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/24x24/logout.png"))); // NOI18N
        btnLogoff.setFocusable(false);
        btnLogoff.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogoff.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoffActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLogoff);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("User Infomation"));

        jLabel16.setText("Full Name");

        txtFullName.setEnabled(false);

        jLabel17.setText("Gender");

        txtGender.setEnabled(false);

        jLabel18.setText("Birthday");

        txtBirthday.setEnabled(false);

        jLabel19.setText("Email");

        txtEmail.setEnabled(false);

        jLabel20.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        txtAddress.setEnabled(false);
        jScrollPane3.setViewportView(txtAddress);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtGender, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel20)))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Work  Information"));

        jLabel9.setText("Current Department:");

        jLabel10.setText("Curent Project");

        txtCurDeparment.setEnabled(false);

        txtCurProject.setEnabled(false);

        jLabel12.setText("Role");

        txtRole.setEditable(false);

        jLabel13.setText("Work Exprience");

        txtWorkExprience.setEditable(false);

        jLabel14.setText("Salary");

        txtSalary.setEditable(false);

        txaCurLocation.setColumns(20);
        txaCurLocation.setEditable(false);
        txaCurLocation.setRows(5);
        jScrollPane4.setViewportView(txaCurLocation);

        jLabel21.setText("Current Location");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel21)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWorkExprience, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(txtCurDeparment, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCurProject, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addComponent(txtRole, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCurDeparment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(txtCurProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtWorkExprience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Employee Profiles", new javax.swing.ImageIcon(getClass().getResource("/Icons/profile.png")), jPanel1); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Information of transfer"));

        jLabel1.setText("Employee:");

        jLabel2.setText("From Location:");

        jLabel3.setText("From Department:");

        jLabel4.setText("From Project:");

        jLabel5.setText("Reason:");

        txtEmployee.setEditable(false);

        txtFromDepartment.setEditable(false);

        txtFromProject.setEditable(false);

        txaReason.setColumns(20);
        txaReason.setRows(5);
        jScrollPane2.setViewportView(txaReason);

        jLabel6.setText("To Location:");

        jLabel7.setText("To Department:");

        jLabel8.setText("To Project:");

        cbToLocation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbToLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToLocationActionPerformed(evt);
            }
        });

        cbToDepartment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbToDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToDepartmentActionPerformed(evt);
            }
        });

        cbToProject.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbToProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbToProjectActionPerformed(evt);
            }
        });

        btnRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/mail_send.png"))); // NOI18N
        btnRequest.setText("Send Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/refresh.png"))); // NOI18N
        btnReset.setText("Reset");

        txaFromLocation.setColumns(20);
        txaFromLocation.setEditable(false);
        txaFromLocation.setRows(5);
        jScrollPane5.setViewportView(txaFromLocation);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(btnRequest)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addContainerGap(356, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbToLocation, 0, 511, Short.MAX_VALUE)
                    .addComponent(cbToDepartment, 0, 511, Short.MAX_VALUE)
                    .addComponent(cbToProject, 0, 511, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFromProject, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(txtFromDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFromDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFromProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbToLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbToDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbToProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnReset)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transfer Request", new javax.swing.ImageIcon(getClass().getResource("/Icons/sendrequest.png")), jPanel2); // NOI18N

        tblHistoryTransfer.setModel(tablemodelHistory);
        tblHistoryTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHistoryTransferMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHistoryTransfer);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 18));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("History Transfer");

        btnViewHistoryDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/accept_page.png"))); // NOI18N
        btnViewHistoryDetails.setText("View History Details");
        btnViewHistoryDetails.setEnabled(false);
        btnViewHistoryDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewHistoryDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(jLabel27)
                .addContainerGap(393, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(btnViewHistoryDetails)
                .addContainerGap(320, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewHistoryDetails)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Transfer History", new javax.swing.ImageIcon(getClass().getResource("/Icons/folder_full.png")), jPanel3); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/banner.jpg"))); // NOI18N

        jMenu1.setText("File");

        jChangePassEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jChangePassEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/process.png"))); // NOI18N
        jChangePassEmployee.setText("Change Password");
        jChangePassEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangePassEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(jChangePassEmployee);

        jLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/logout.png"))); // NOI18N
        jLogout.setText("Logout");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jLogout);

        jExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/16x16/delete.png"))); // NOI18N
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });
        jMenu1.add(jExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jAbout.setText("Tutorial");
        jAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAboutActionPerformed(evt);
            }
        });
        jMenu2.add(jAbout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, 0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        try {
            // TODO add your handling code here:
            if (cbToDepartment.getSelectedIndex() == 0 || cbToLocation.getSelectedIndex() == 0 || cbToProject.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Please Select Information");
            } else {
                sendRequestTransfer();
                JOptionPane.showMessageDialog(rootPane, "Send request success!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void cbToLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToLocationActionPerformed
        try {
            // TODO add your handling code here:
            toLocationID = LocationDAO.getLocationID((String) cbToLocation.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbToLocationActionPerformed

    private void cbToDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToDepartmentActionPerformed
        try {
            // TODO add your handling code here:
            toDepartmentID = DepartmentDAO.getDepartmentID((String) cbToDepartment.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbToDepartmentActionPerformed

    private void cbToProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbToProjectActionPerformed
        try {
            // TODO add your handling code here:
            toProjectID = ProjectDAO.getProjectID((String) cbToProject.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_cbToProjectActionPerformed

    private void tblHistoryTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHistoryTransferMouseClicked
        try {
            // TODO add your handling code here:
            transferID = Integer.parseInt(tblHistoryTransfer.getValueAt(tblHistoryTransfer.getSelectedRow(), 0).toString());
            objTransfer = TransferDAO.getTransferByID(transferID);
            btnViewHistoryDetails.setEnabled(true);
            if (evt.getClickCount() == 2) {
                TransferHistory transferHistory = new TransferHistory();
                transferHistory.setLocationRelativeTo(transferHistory);
                transferHistory.loadTransferHistoryDetails(objTransfer);
                transferHistory.setVisible(true);
            }
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblHistoryTransferMouseClicked

    private void btnViewHistoryDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewHistoryDetailsActionPerformed
        try {
            // TODO add your handling code here:
            objTransfer = objTransfer = TransferDAO.getTransferByID(transferID);
            TransferHistory transferHistory = new TransferHistory();
            transferHistory.setLocationRelativeTo(transferHistory);
            transferHistory.loadTransferHistoryDetails(objTransfer);
            transferHistory.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnViewHistoryDetailsActionPerformed

    private void jAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAboutActionPerformed
        About ab = new About();
        ab.setLocationRelativeTo(ab);
        ab.setVisible(true);
}//GEN-LAST:event_jAboutActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
        System.exit(0);
}//GEN-LAST:event_jExitActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        LoginSystem log = new LoginSystem(this, true);
        log.setLocationRelativeTo(log);
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_jLogoutActionPerformed

    private void jChangePassEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangePassEmployeeActionPerformed
        ChangePassE cpe = new ChangePassE();
        cpe.setOldPass(oldPassword);
        cpe.setTitle("Employee Change Password");
        cpe.lblHeader.setText("Employee Change Password");
        cpe.setLocationRelativeTo(cpe);
        cpe.setVisible(true);
}//GEN-LAST:event_jChangePassEmployeeActionPerformed

    private void btnLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoffActionPerformed
        // TODO add your handling code here:
        LoginSystem log = new LoginSystem(this, true);
        log.setLocationRelativeTo(log);
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btnLogoffActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        ChangePassE cpe = new ChangePassE();
        cpe.setOldPass(oldPassword);
        cpe.setLocationRelativeTo(cpe);
        cpe.setVisible(true);
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        About ab = new About();
        ab.setLocationRelativeTo(ab);
        ab.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
//                new MainEmployee().setVisible(true);
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MainEmployee.class.getName()).log(Level.SEVERE, null, ex);
                }
                LoginSystem login = new LoginSystem(null, true);
                login.setLocationRelativeTo(login);
                login.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnHelp;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnViewHistoryDetails;
    private javax.swing.JComboBox cbToDepartment;
    private javax.swing.JComboBox cbToLocation;
    private javax.swing.JComboBox cbToProject;
    private javax.swing.JMenuItem jAbout;
    private javax.swing.JMenuItem jChangePassEmployee;
    private javax.swing.JMenuItem jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jLogout;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailContent;
    private javax.swing.JTable tblHistoryTransfer;
    private javax.swing.JTextArea txaCurLocation;
    private javax.swing.JTextArea txaFromLocation;
    private javax.swing.JTextArea txaReason;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtCurDeparment;
    private javax.swing.JTextField txtCurProject;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployee;
    private javax.swing.JTextField txtFromDepartment;
    private javax.swing.JTextField txtFromProject;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtRole;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtWorkExprience;
    // End of variables declaration//GEN-END:variables
}
